#!/bin/sh
export PATH=/opt/homebrew/bin:/usr/local/bin:$PATH
swiftformat --version 1>/dev/null 2>&1

git-format-staged --formatter "swiftformat --config ~/swiftformat-pace.config stdin --stdinpath '{}'" "*.swift"
