#!/bin/sh
export PATH=/opt/homebrew/bin:/usr/local/bin:$PATH
swift-format --version 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
    git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
        swift-format --configuration ~/swift-format-pace.config -i "${line}";
        git add "$line";
    done
fi